version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: veel-events/Dockerfile
    container_name: client_container
    ports:
      - "80:80"
  server:
    build:
      context: .
      dockerfile: veel-event-api/Dockerfile
    container_name: server_container
    ports:
      - "3000:3000"