version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: veel-events/Dockerfile
    ports:
      - "5173:5173"
    container_name: client_container
    networks:
      - default
  server:
    build:
      context: .
      dockerfile: veel-event-api/Dockerfile
    container_name: server_container
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
